// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$P(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "mb-2"
            }, children);
}

var P = {
  make: Index$P
};

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-3xl font-semibold"
                }, "What is this about?"), React.createElement("p", undefined, "This is a simple template for a Next project using Rescript"), React.createElement("h2", {
                  className: "text-2xl font-semibold mt-5"
                }, "Quick Start"));
}

export {
  P ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
