// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var $$Document = {};

function Example$Page(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setText = match$1[1];
  var text = match$1[0];
  React.useEffect(function () {
        document.title = "You clicked " + String(count) + " times";
        
      });
  React.useEffect((function () {
          if (text === "") {
            Curry._1(setText, (function (param) {
                    return "test";
                  }));
          }
          
        }), [text]);
  var onClick = function (_evt) {
    return Curry._1(setCount, (function (prev) {
                  return prev + 1 | 0;
                }));
  };
  var onClickText = function (_evt) {
    return Curry._1(setText, (function (param) {
                  return "Hanseung";
                }));
  };
  var msg = "You clicked" + String(count) + "times";
  return React.createElement("div", undefined, React.createElement("p", undefined, msg), React.createElement("button", {
                  onClick: onClick
                }, "Click me"), React.createElement("div", undefined, "Hello" + text), React.createElement("button", {
                  onClick: onClickText
                }, "Click change name!!"));
}

var Page = {
  make: Example$Page
};

function $$default(param) {
  return React.createElement(Example$Page, {});
}

export {
  $$Document ,
  Page ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
