// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var greeting = "Hello";

var name = "Stranger";

var element = React.createElement("div", {
      className: "myElement"
    }, greeting, name);

export {
  greeting ,
  name ,
  element ,
  
}
/* element Not a pure module */
