// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext(/* Light */0);

var provider = context.Provider;

function ContextPage$ThemeContext$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: ContextPage$ThemeContext$Provider
};

var ThemeContext = {
  context: context,
  Provider: Provider
};

function ContextPage$Button(Props) {
  var theme = Props.theme;
  var className = theme ? "theme-black" : "theme-light";
  return React.createElement("button", {
              className: className
            }, "Click me");
}

var Button = {
  make: ContextPage$Button
};

function ContextPage$ThemedButton(Props) {
  var theme = React.useContext(context);
  return React.createElement(ContextPage$Button, {
              theme: theme
            });
}

var ThemedButton = {
  make: ContextPage$ThemedButton
};

function ContextPage$Toolbar(Props) {
  return React.createElement("div", undefined, React.createElement(ContextPage$ThemedButton, {}));
}

var Toolbar = {
  make: ContextPage$Toolbar
};

function ContextPage(Props) {
  return React.createElement(ContextPage$ThemeContext$Provider, {
              value: /* Dark */1,
              children: React.createElement("div", undefined, React.createElement(ContextPage$Toolbar, {}))
            });
}

var make = ContextPage;

export {
  ThemeContext ,
  Button ,
  ThemedButton ,
  Toolbar ,
  make ,
  
}
/* context Not a pure module */
