service: nextjs-serverless

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-domain-manager

# include:
#   - .next/**
#   - public/**
#   - server.js

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
  webpack:
    webpackConfig: webpack.server.js
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ${file(./config.json):region}
  vpc: ${file(./config.json):vpc}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'
  resourcePolicy:
    - Effect: 'Allow'
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        StringEquals:
          aws:sourceVpce:
            - ${file(./config.json):vpce}

functions:
  server:
    description: nextjs-serverless server handler
    handler: src/server/serverless.handler
    memorySize: 128
    tracing: true
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
