// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Greeting(Props) {
  var name = Props.name;
  var greeting = name !== undefined ? "Hello" + name + "!" : "Hello stranger!";
  return React.createElement("div", undefined, greeting);
}

var make = Greeting;

export {
  make ,
  
}
/* react Not a pure module */
