// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Greeting from "../../components/Greeting/Greeting.mjs";
import * as Router from "next/router";

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  if (match === "/examples") {
    return React.createElement("div", undefined, React.createElement("h1", {
                    className: "font-bold"
                  }, "Examples Section"), React.createElement("div", undefined, content));
  } else {
    return React.createElement("div", undefined, React.createElement(Greeting.make, {}), content);
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
