service: nextjs-serverless

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8080
    useChildProcess: true
  webpack:
    webpackConfig: webpack.server.js

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ${file(./config.json):region}
  vpc: ${file(./config.json):vpc}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'
  resourcePolicy:
    - Effect: 'Allow'
      Principal: '*'
      Action: excute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        StringEquals:
          aws:sourceVpce:
            - ${file(./config.json):vpce}

functions:
  server:
    description: nextjs-serverless server handler
    handler: src/server/serverless.handler
    memorySize: 128
    tracing: true
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
