# This GitHub Actions workflow runs on manual trigger on a branch of a
# repository, and configures the React app in the AWS Amplify Console.
#
# First, the GitHub Action deploys the 'stack.yaml' AWS CloudFormation stack
# to your AWS Account. This stack configures the React app in the AWS Amplify Console.
#
# Then, you need to trigger a first build in the AWS Amplify Console to
# fully configure it.

name: Deploy

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'ap-northeast-2'

jobs:
  amplify-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -X POST -d {} "https://webhooks.amplify.ap-northeast-2.amazonaws.com/prod/webhooks?id=5d912f30-d827-4c75-a9ee-a32254d4b526&token=StJgQUQU7B7P7DsUgD0p1QhtcQUblSB7GNoX5IA7BM&amp;operation=startbuild" -H "Content-Type:application/json"
