name: 'Serverless lambda deploy'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포 환경 선택'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - prod

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: repo checkout
        uses: actions/checkout@v1
        with:
          path: lambda

      - name: aws credential settings
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: rush global install
        run: npm i -g @microsoft/rush

      - name: rush update
        run: rush update

      - name: project deploy
        run: rush deploy --project next-serverless-app

      # - name: project npm install
      #   working-directory: ./common/deploy/apps/next-serverless-app
      #   run: npm install

      - name: project build
        working-directory: ./common/deploy/apps/next-serverless-app
        run: npm run build

      - name: project lambda deploy
        working-directory: ./common/deploy/apps/next-serverless-app
        run: npm run deploy

      # - name: serverless deploy
      #   uses: serverless/github-action@v3
      #   with:
      #     args: deploy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
