name: Test trigger

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      apps:
        type: choice
        description: '타겟 App'
        options:
          - Admin
          - Webview

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.apps }}"
